### ISSUE TITLE
NTR breaks server lists

### ISSUE THREAD

**Issue by ghost** [Kaiddd/NTR#2]
![image](https://user-images.githubusercontent.com/49875377/208482221-c850bff1-f073-4bc7-b0a4-3dad90bdb892.png)
![image](https://user-images.githubusercontent.com/49875377/208482230-7dc22434-dac0-4b81-b30c-6f66233d3520.png)

**Comment by Kaiddd** [comment]
Fixed in https://github.com/Kaiddd/NTR/commit/3c166dbb6f6ddc947f16902faf9d8e486e7f0a07
